[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/bluehost/"
  to = "https://bluehost.sjv.io/do4QeK"
  status = 301

[[redirects]]
  from = "/install-jekyll/"
  to = "/install-jekyll-on-macos/"
  status = 301

[[redirects]]
  from = "/google-firebase-hosting-jekyll/"
  to = "/firebase-hosting-jekyll/"
  status = 301

[[redirects]]
  from = "/jekyll-firebase-hosting/"
  to = "/firebase-hosting-jekyll/"
  status = 301

# Temporary Redirects
[[redirects]]
  from = "/what-s-new-in-jekyll-3-4-0/"
  to = "/what-s-new-in-jekyll-3-4/"
  status = 301

[[redirects]]
from = "/google-analytics-for-jekyll/"
to = "/google-analytics-jekyll/"
status = 301

[[redirects]]
from = "/disqus-comments-setup-for-jekyll/"
to = "/disqus-comments-jekyll/"
status = 301

[[redirects]]
from = "/how-to-create-a-static-website-with-ghost/"
to = "/static-website-with-ghost/"
status = 301
